import React from "react";
import { t } from "../../theme";

export const S = {
  card: {
    background:   t.bg.app,
    border:       `1px solid ${t.border.subtle}`,
    borderRadius: t.radius.lg,
    overflow:     "hidden" as const,
  },
  cardHeader: {
    padding:      "10px 16px",
    background:   t.bg.s1,
    borderBottom: `1px solid ${t.border.subtle}`,
    display:      "flex"   as const,
    alignItems:   "center" as const,
    gap:          10,
  },
  cardBody: {
    padding:       16,
    display:       "flex"   as const,
    flexDirection: "column" as const,
    gap:           12,
  },
  row2: { display: "grid" as const, gridTemplateColumns: "1fr 1fr",   gap: 10 },
  row3: { display: "grid" as const, gridTemplateColumns: "1fr 1fr 1fr", gap: 10 },
  field: { display: "flex" as const, flexDirection: "column" as const, gap: 4 },
  label: {
    fontSize:      t.size.sm,
    color:         t.text.muted,
    fontWeight:    600 as const,
    letterSpacing: 0.3,
  },
  input: {
    background:   t.bg.s2,
    border:       `1px solid ${t.border.base}`,
    borderRadius: t.radius.md,
    color:        t.text.primary,
    padding:      "7px 10px",
    fontSize:     t.size.md,
    width:        "100%",
  },
  select: {
    background:   t.bg.s2,
    border:       `1px solid ${t.border.base}`,
    borderRadius: t.radius.md,
    color:        t.text.primary,
    padding:      "7px 10px",
    fontSize:     t.size.md,
    width:        "100%",
    cursor:       "pointer" as const,
  },
  btnPrimary: {
    background:   t.blue.base,
    border:       "none",
    borderRadius: t.radius.md,
    color:        t.text.inverse,
    padding:      "6px 14px",
    fontSize:     t.size.base,
    fontWeight:   600 as const,
    cursor:       "pointer" as const,
  },
  btnSecondary: {
    background:   t.bg.s2,
    border:       `1px solid ${t.border.base}`,
    borderRadius: t.radius.md,
    color:        t.text.secondary,
    padding:      "6px 14px",
    fontSize:     t.size.base,
    fontWeight:   600 as const,
    cursor:       "pointer" as const,
  },
  // ── Danger / Success use alpha-tinted variants; alpha cannot pass through
  // CSS var() concatenation, so the alpha forms stay as literal hex values.
  btnDanger: {
    background:   `${t.red.border}33`,
    border:       `1px solid ${t.red.border}88`,
    borderRadius: t.radius.md,
    color:        t.red.fg,
    padding:      "6px 14px",
    fontSize:     t.size.base,
    fontWeight:   600 as const,
    cursor:       "pointer" as const,
  },
  btnSuccess: {
    background:   `${t.green.base}22`,
    border:       `1px solid ${t.green.base}55`,
    borderRadius: t.radius.md,
    color:        t.green.fg,
    padding:      "6px 14px",
    fontSize:     t.size.base,
    fontWeight:   600 as const,
    cursor:       "pointer" as const,
  },
  badge: (bg: string, fg: string): React.CSSProperties => ({
    padding:      "2px 8px",
    borderRadius: 10,
    fontSize:     t.size.xs,
    fontWeight:   600,
    background:   bg,
    color:        fg,
    whiteSpace:   "nowrap",
  }),
  th: {
    padding:    "6px 10px",
    textAlign:  "left" as const,
    color:      t.text.muted,
    fontWeight: 500,
    fontSize:   t.size.base,
    whiteSpace: "nowrap" as const,
  },
  td: { padding: "5px 10px", fontSize: t.size.base },
  trBorder: { borderBottom: `1px solid ${t.bg.s2}` },
};
